version: "3.8"
services:
    web:
        depends_on:
            - api
        image: ${FRONT_IMAGE_NAME} #frontend
        ports:
            - ${FRONT_PORT}:3000
    api:
        depends_on:
            - db
        image: ${BACK_IMAGE_NAME} #backend
        ports:
            - ${BACK_PORT}:5000
        environment:
            - DB_URL=mongo://db:${DB_PORT}//chat
    db:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
            MONGO_INITDB_DATABASE: chat
        ports:
            - ${DB_PORT}:27017
        volumes:
            - chat:/data/db
volumes:
    chat:
  
  


