version: "3.8"
services:
  web:
    depends_on:
      - api
    image: ${FRONT_IMAGE_NAME} #frontend
    ports:
      - 3000:3000
  api:
    depends_on:
      - db
    image: ${BACK_IMAGE_NAME} #backend
    ports:
      - 5000:5000
    environment:
      - DB_URL=mongo://db//vidly
  db:
    image: mongo
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: rootpassword
       MONGO_INITDB_DATABASE: chat
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
volumes:
  vidly:
  
  


