version: "3.8"
services:
  web:
    depends_on:
      - api
    image: ${FRONT_IMAGE_NAME} #frontend
    ports:
      - ${env.FRONT_PORT}:3000
  api:
    depends_on:
      - db
    image: ${BACK_IMAGE_NAME} #backend
    ports:
      - ${env.BACK_PORT}:5000
    environment:
      - DB_URL=mongo://db//chat
  db:
    image: mongo
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: rootpassword
       MONGO_INITDB_DATABASE: chat
    ports:
      - 27017:27017
    volumes:
      - chat:/data/db
volumes:
  chat:
  
  


